version: "3.9"

services:
  authorservice:
    image: authorservice:local
    build:
      context: .
    environment:
      APP_DATABASE_HOST: authordb
      APP_DATABASE_PASSWORD: 1234
      APP_DATABASE_DBNAME: postgres
    ports:
    - "8080:8080"
    depends_on:
    - authordb

  authordb:
    image: postgres:14.5-alpine3.16
    environment:
      POSTGRES_PASSWORD: 1234
    configs:
    - source: postgres-schema
      target: /docker-entrypoint-initdb.d/schema.sql
    volumes:
    - postgres-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"

configs:
  postgres-schema:
    file: sql/schema.sql

volumes:
  postgres-data: